#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

promptinit
prompt paradoxmod
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:git*:*' get-revision true
zstyle ':vcs_info:git*:*' check-for-changes true

source ~/.commonrc

# for some godforsaken reason, this was necessary to enable history-beginning-search:
#   (see also: https://unix.stackexchange.com/a/100860)

bindkey "^[OA" history-beginning-search-backward
bindkey "^[OB" history-beginning-search-forward

